# Generated by Django 3.2.7 on 2021-11-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211118_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipad',
            name='cam_mp',
        ),
        migrations.RemoveField(
            model_name='iphone',
            name='accum_volume',
        ),
        migrations.AddField(
            model_name='iphone',
            name='battery',
            field=models.CharField(blank=True, max_length=255, verbose_name='Power and Battery'),
        ),
        migrations.AddField(
            model_name='iphone',
            name='chip',
            field=models.CharField(blank=True, max_length=255, verbose_name='Частота процессора'),
        ),
        migrations.AddField(
            model_name='iphone',
            name='interfaces',
            field=models.CharField(blank=True, max_length=255, verbose_name='Interfaces'),
        ),
        migrations.AddField(
            model_name='iphone',
            name='sensors',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sensors'),
        ),
        migrations.AddField(
            model_name='iphone',
            name='sim_card',
            field=models.CharField(blank=True, max_length=255, verbose_name='SIM Card'),
        ),
        migrations.AddField(
            model_name='iphone',
            name='weight',
            field=models.CharField(blank=True, max_length=255, verbose_name='Size and Weight'),
        ),
        migrations.AddField(
            model_name='iphone',
            name='wireless',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cellular and Wireless'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='frontal_cam_mp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фронтальная камера'),
        ),
    ]
