# Generated by Django 3.2.7 on 2021-11-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211122_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipad',
            name='accum_volume',
        ),
        migrations.RemoveField(
            model_name='ipad',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='ipad',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='ipad',
            name='frontal_cam_mp',
        ),
        migrations.RemoveField(
            model_name='ipad',
            name='main_cam_mp',
        ),
        migrations.RemoveField(
            model_name='ipad',
            name='mamory',
        ),
        migrations.RemoveField(
            model_name='ipad',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='ipad',
            name='resolution',
        ),
        migrations.AddField(
            model_name='ipad',
            name='battery_and_power',
            field=models.TextField(blank=True, max_length=255, verbose_name='Battery and Power'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='camera',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Camera'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='chip',
            field=models.TextField(blank=True, max_length=255, verbose_name='Chip'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='color',
            field=models.TextField(blank=True, max_length=200, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='display',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='sensors',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Sensors'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='sim_card',
            field=models.TextField(blank=True, max_length=255, verbose_name='SIM Card'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='toch_id',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Touch ID'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='weight',
            field=models.TextField(blank=True, max_length=255, verbose_name='Size and Weight'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='wireless',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Cellular and Wireless'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='memory',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='display',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Display'),
        ),
    ]
