# Generated by Django 3.2.7 on 2021-11-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211122_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iphone',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='iphone',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='iphone',
            name='resolution',
        ),
        migrations.AddField(
            model_name='iphone',
            name='color',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='iphone',
            name='display',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Display'),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='battery_and_power',
            field=models.TextField(blank=True, max_length=2555, verbose_name='Battery and Power'),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='chip',
            field=models.TextField(blank=True, max_length=2555, verbose_name='Chip'),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='color',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='sim_card',
            field=models.TextField(blank=True, max_length=2555, verbose_name='SIM Card'),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='weight',
            field=models.TextField(blank=True, max_length=2555, verbose_name='Size and Weight'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='chip',
            field=models.TextField(blank=True, max_length=2555, verbose_name='Chip'),
        ),
    ]
